evangelisation/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from evangelisation import views



app_name="notification"


urlpatterns = [
    path('messages/', 
        views.notification_app_index, 
        name="notification_app_index"
    ),

    path('messages/<int:pk>/detail', 
        views.notification_app_index, 
        name="notification_app_index"
    ),

    path('messages/<int:pk>/supprimer', 
        views.notification_app_delete, 
        name="notification_app_delete"
    ),

    path('messages/recherche', 
        views.notification_app_recherche, 
        name="notification_app_recherche"
    ),

    path('personnes/ajouter', 
        views.notification_app_ajouter_personne, 
        name="notification_app_ajouter_personne"
    ),

    path('personnes/<int:pk>/modifier', 
        views.notification_app_detail_personne, 
        name="notification_app_detail_personne"
    ),
    

    path('personnes/<int:pk>/supprimer', 
        views.notification_app_supprimer_personne, 
        name="notification_app_supprimer_personne"
    ),
            
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from evangelisation import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('', 
        views.notification_app_index, 
        name="notification_app_index"
    ),
    path('notification/', include("evangelisation.urls")),
]

urlpatterns += static(settings.STATIC_URL,   document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL,   document_root=settings.MEDIA_ROOT)

evangelisation/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.utils.text import slugify



#override username(max_length, help_text), email(_unique) and password(max_length, help_text)
User._meta.get_field('username').validators[1].limit_value = 150
User._meta.get_field('email')._unique = True
User._meta.get_field('username').help_text = 'Obligatoire. 150 caractères ou moins. Lettres, chiffres et @/./+/-/_ uniquement.'
User._meta.get_field('password').help_text = 'Il doit contenir au moins 8 caractères.<br> Ne doit pas etre courant.<br> doit etre alphanuméric'


#==========Participants à l'évangelisation
class Personne(models.Model):
    SEXE = (
        ('masculin', 'Masculin'),
        ('féminin', 'Féminin')
    )
    nom_et_prenom = models.CharField(max_length=200, unique=True, error_messages={'unique':"Une personne avec ce nom et\ou prénom existe déjà"})
    sexe = models.CharField(choices=SEXE, max_length=15, 
    verbose_name='Sexe')
    telephone = models.PositiveIntegerField(unique=True, 
                error_messages={'unique':"Une personne avec ce numéro de télephone existe déjà"})
   
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.nom_et_prenom


class Message(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    author = models.ForeignKey(
        User, 
        related_name='personnes', 
        on_delete=models.DO_NOTHING, 
    )
    receiver_message = models.ManyToManyField(
        Personne, 
        related_name='messages',
        verbose_name="Liste des personnes",
        help_text="Selectionner ceux qui vont recevoir le message"
    )
    publish = models.DateTimeField(default=timezone.now)
    body = models.TextField(
        verbose_name="Contenu",
        help_text="Votre message"
    )

    class Meta:
        ordering = ('-publish',)
        
    def __str__(self):
        return f"Message du {self.publish}"



#==========Profile utilisateur
class Profile(models.Model):
    SEXE = (
        ('masculin', 'Masculin'),
        ('féminin', 'Féminin')
    )
    user = models.OneToOneField(User, on_delete=models.SET_NULL, blank=True,  null=True)
    image = models.ImageField(upload_to='images/profile/%Y/', null=True, blank=True, help_text="ajouter une photo")
    phone = models.PositiveIntegerField(null=True, unique=True, blank=True, 
        help_text="le numéro de télephone doit avoir 9 chiffres",
        error_messages={'unique':"Une boss avec ce numéro de télephone existe déjà"})
    sexe = models.CharField(choices=SEXE, max_length=15, verbose_name='Sexe')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Profile de {self.user}"

evangelisation/forms.py
from django import forms

from evangelisation.models import Personne, Message


#==================================================================================
#===========================Personne form
class PersonneForm(forms.ModelForm):
    class Meta:
        model = Personne
        fields = ['nom_et_prenom', 'telephone', 'sexe']

    def clean_nom_et_prenom(self):
        nom_et_prenom = self.cleaned_data['nom_et_prenom']
        if len(str(nom_et_prenom))<3:
            raise forms.ValidationError("Problème lors du remplissage du nom et prenom d'un participant : Le champ doit avoir au moins 03 caractères ")
        return nom_et_prenom
    
    def clean_telephone(self):
        telephone = self.cleaned_data['telephone']
        if len(str(telephone))!=9:
            raise forms.ValidationError("Le numéro de télephone est invalide")
        else:
            if len(str(telephone))==9:
                telephone_6 = str(telephone)[0]
                if int(telephone_6)!=6:
                    raise forms.ValidationError("Le numéro de télephone doit commencer par 6")
        return telephone



class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['receiver_message', 'body']
    
    def clean_receiver(self):
        return [self.receiver_message]


class FormNbre(forms.Form):
    formulaires = forms.IntegerField(label="Entrez le nombre de formulaire que vous voulez", help_text="le nombre de formulaire sera crée")

evangelisation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import modelformset_factory
from django.http import JsonResponse
from django.http.response import Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from twilio.rest import Client

from evangelisation.forms import PersonneForm, MessageForm, FormNbre
from evangelisation.models import Message, Personne

from evangelisation.send_sms import send_sms


@login_required(login_url="user_login")
def notification_app_index(request, pk=None):
    context = dict()
    form = None
    message = None
    messages_send = None
    personnes = None
    messages_select = None

    if pk:
        try:
            message = Message.objects.get(id=pk)
        except Message.DoesNotExist:
            raise Http404("Pages non disponible")

    if request.method=='POST':
        if pk:
            form = MessageForm(data=request.POST, instance=message)
        else:
            form = MessageForm(request.POST)
        if form.is_valid():
            if pk:
                form.save()
                is_error = send_sms(message)
                if is_error:
                    messages.error(request, f"une erreur s'est produit durant l'envoie du SMS : ce numéro n'est pas encore accepté par le service(Twilio) des SMS")
                else:
                    messages.success(request, f"Modification et SMS renvoyé avec success!!")
                return redirect('notification:notification_app_index')
            else:
                message = form.save(commit=False)
                message.author = request.user
                message.save()
                form.save_m2m()
                is_error = send_sms(message)
                if is_error:
                    messages.error(request, f"une erreur s'est produit durant l'envoie du SMS : ce numéro n'est pas encore accepté par le service(Twilio) des SMS")
                else:
                    messages.success(request, f"Votre SMS a été envoyé avec success!!")
                return redirect('notification:notification_app_index')
    else:
        if pk:
            form = MessageForm(instance=message)
            messages_send = Message.objects.all()
            context['modifié'] = True
            context['message'] = message
            
        else:
            if 'liste-message' in request.GET:
                try:
                    message = Message.objects.get(id=int(request.GET['liste-message']))
                    messages_send = Message.objects.filter(publish=message.publish)
                    context['msg_select'] = message
                except Message.DoesNotExist:
                    raise Http404("Pages non disponible")
            else:
                messages_send = Message.objects.all()
            form = MessageForm()
        context['form'] = form
        context['messages_send'] = messages_send
        context['messages_select'] = Message.objects.all()
        context['personnes'] = Personne.objects.all()
        context['select_link'] = 'sms'
    return render(request, 'index.html', context)



@login_required(login_url="user_login")
def notification_app_delete(request, pk):
    msg = get_object_or_404(Message, id=pk)
    msg.delete()
    messages.error(request, f"Supprission reuissie du message")
    return redirect('notification:notification_app_index')




@login_required(login_url="user_login")
def notification_app_recherche(request):
    context = dict()
    messages_send = None
    if 'liste-message' in request.GET:
        try:
            message = Message.objects.get(id=int(request.GET['liste-message']))
            messages_send = Message.objects.filter(publish=message.publish)
        except Message.DoesNotExist:
            raise Http404("Pages non disponible")

    form = MessageForm()
    context['form'] = form
    context['message'] = message
    context['messages_send'] = messages_send
    return redirect('notification:notification_app_index')



@login_required(login_url="user_login")
def notification_app_ajouter_personne(request):
    context = dict()
    form = None
    if request.method=='POST':
        form = PersonneForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f"Personne ajouté avec successe!!")
            return redirect('notification:notification_app_ajouter_personne')
    else:
        form = PersonneForm()
    context['form'] = form
    context['select_link'] = 'sms'
    return render(request, 'pages/personne/personne.html', context)


@login_required(login_url="user_login")
def notification_app_detail_personne(request, pk):
    context = dict()
    form = None
    try:
        personne = Personne.objects.get(id=pk)
    except Personne.DoesNotExist:
        raise Http404("Pages non disponible")
    if request.method=='POST':
        form = PersonneForm(data=request.POST, instance=personne)
        if form.is_valid():
            form.save()
            messages.success(request, f"Personne modification reuissie!!")
            return redirect('notification:notification_app_index')
    else:
        form = PersonneForm(instance=personne)
        context['modifier'] = True
        context['personne'] = personne
    context['form'] = form
    context['select_link'] = 'sms'
    return render(request, 'pages/personne/personne.html', context)


@login_required(login_url="user_login")
def notification_app_supprimer_personne(request, pk):
    personne = get_object_or_404(Personne, id=pk)
    for msg in personne.messages.all():
        msg.delete()
    personne.delete()
    messages.error(request, f"Supprission reuissie de la personne")
    return redirect('notification:notification_app_index')

evangelisation/templates/pages/personne/personne.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block titre %}
    vh-cam|Personnes
{% endblock titre %}



{% block hamburger %}
    <div class="menu-btn">
        <i class="fas fa-bars"></i>
        <i class="fas fa-times"></i>
    </div>
{% endblock hamburger %}



{% block sidebar %}
    {% include 'layouts/_sidebar.html' %}
{% endblock sidebar %}



{% block content %}
<div class="home">
    <div class="wrapper-head-liste">
        <div class="head-liste">
            <h2>
                {% if modifier %}
                    Modifier {{personne}}
                {% else %}
                    Ajouter des personnes
                {% endif %}
            </h2>
            <h4>Personnes</h4>
        </div>
    </div>
    {% if messages %}
    <div class="wrapper-evang">
        <div class="row">
            <div class="form-group">
                <ul class="messages">
                    {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="row">
        <form id="form-suppresion-liste" 
                action="
                {% if modifier %}
                    {% url 'notification:notification_app_detail_personne' personne.id %}
                {% else %}
                    {% url 'notification:notification_app_ajouter_personne' %}
                {% endif %}" 
                method="post" 
                class="form-group row">
            {% csrf_token %}
            
            <div class="row">
                <div class="col-md-12">
                    <div class="wrapper-form-personne">
                        <div class="personne-fields">
                            {% for field in form %}
                            <div class="form-group {% if field.errors %}has-error{% endif %}" style="overflow: auto;">
                                <div class="form-field">
                                    <label for="{{ field.id_for_label }}">{{field.label}}</label> 
                                    {% render_field field class="form-control" %}
                                    <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% for error in field.errors %}
                                        <p class="pt-2 pb-2 pl-2 pr-2" style="background-color: #dc3545;border-radius: 7px;">
                                            {{ error }}
                                        </p>
                                    {% endfor %} 
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="wrapper-btn-formset">
                        {% if modifier %}
                        <input type="submit" value="Modifier les informations" name="submit" class="btn btn-success btn-sm">
                        <a href="{% url 'notification:notification_app_index' %}"
                            class="btn btn-secondary btn-sm">Retour</a>
                        <a href="{% url 'notification:notification_app_supprimer_personne' personne.id %}"
                            class="btn btn-danger btn-sm">Supprimer</a>
                        {% else %}
                        <input type="submit" value="Ajouter" name="submit" class="btn btn-success btn-sm">
                        <a href="{% url 'notification:notification_app_index' %}"
                            class="btn btn-secondary btn-sm">Annuler</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}